import {getLevelCompletionReward, MATCH_REWARD} from './coinRewards';

export const PRODUCT_ASSETS = {
  apple: require('../assets/splash elements/apple without bg.png'),
  milk: require('../assets/splash elements/milk bottle without bg.png'),
  juice: require('../assets/splash elements/orange bottle wthout bg.png'),
  can: require('../assets/splash elements/red bottle without bg.png'),
  blueMilk: require('../assets/merglix game elments/blue milk bottle.png'),
  blueJuice: require('../assets/merglix game elments/blue juice bottle.png'),
  orangeBottle: require('../assets/merglix game elments/orange bottle.png'),
  redChips: require('../assets/merglix game elments/red chips cane.png'),
  greenHerbal: require('../assets/merglix game elments/Green herbal bottle.png'),
  blueFruit: require('../assets/merglix game elments/blue fruit bottle.png'),
  greenBottle: require('../assets/merglix game elments/Green bottle.png'),
  greenFruit: require('../assets/merglix game elments/green fruit bottle.png'),
  level3Milk: require('../assets/merglix game elments/milk bottle.png'),
  orangeBottleAlt: require('../assets/merglix game elments/orange bottle-1.png'),
  orangeCan: require('../assets/merglix game elments/orange cane.png'),
  teddy: require('../assets/merglix game elments/Artboard 3.png'),
  duck: require('../assets/merglix game elments/Artboard 4.png'),
  corn: require('../assets/merglix game elments/corn.png'),
  grapes: require('../assets/merglix game elments/Grapes.png'),
  lemon: require('../assets/merglix game elments/lemon.png'),
  pineapple: require('../assets/merglix game elments/Pineapple.png'),
  sooperBiscuit: require('../assets/merglix game elments/sooper biscuit.png'),
  watermelon: require('../assets/merglix game elments/watermelon.png'),
  strawberry: require('../assets/merglix game elments/stabbery.png'),
};

export const SHELF_ASSETS = {
  classic3: require('../assets/cupboard with 3 shelf.png'),
  classic4: require('../assets/cupboard with 4 shelf.png'),
  classic5: require('../assets/merglix game elments/cupboard with 5 shelf.png'),
  classic6: require('../assets/merglix game elments/cupboard with 6 shelf.png'),
};

export function getLevelTimerSeconds(level) {
  const safeLevel = Math.max(1, Math.floor(Number(level) || 1));
  return 60 + Math.floor((safeLevel - 1) / 10) * 10;
}

function levelConfig({level, rows, columns, productTypes, copiesByType,
  difficulty, targetMatches}) {
  const totalItemCount = Object.values(copiesByType)
    .reduce((total, count) => total + count, 0);
  const durationSeconds = getLevelTimerSeconds(level);
  return {
    id: level,
    level,
    rows,
    columns,
    shelfCount: rows,
    productTypes,
    productTypeCount: productTypes.length,
    copiesByType,
    matchSize: 3,
    matchCount: targetMatches,
    targetMatches,
    totalItemCount,
    matchReward: MATCH_REWARD,
    completionReward: getLevelCompletionReward(level),
    durationSeconds,
    timerSeconds: durationSeconds,
    difficulty,
    shelf: `classic${rows}`,
    generatedShelves: false,
  };
}

export const LEVEL_CONFIGS = {
  1: levelConfig({level: 1, rows: 3, columns: 4,
    productTypes: ['apple', 'milk', 'can'],
    copiesByType: {apple: 6, milk: 3, can: 3},
    targetMatches: 4, difficulty: 'tutorial'}),
  2: levelConfig({level: 2, rows: 3, columns: 5,
    productTypes: ['apple', 'milk', 'can'],
    copiesByType: {apple: 6, milk: 6, can: 3},
    targetMatches: 5, difficulty: 'very-easy'}),
  3: levelConfig({level: 3, rows: 3, columns: 5,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesByType: {apple: 6, milk: 3, juice: 3, can: 3},
    targetMatches: 5, difficulty: 'easy'}),
  4: levelConfig({level: 4, rows: 3, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesByType: {apple: 6, milk: 6, juice: 3, can: 3},
    targetMatches: 6, difficulty: 'easy'}),
  5: levelConfig({level: 5, rows: 4, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesByType: {apple: 6, milk: 6, juice: 6, can: 6},
    targetMatches: 8, difficulty: 'easy-plus'}),
  6: levelConfig({level: 6, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'redChips'],
    copiesByType: {blueFruit: 6, blueJuice: 6, blueMilk: 6, greenHerbal: 3, redChips: 3},
    targetMatches: 8, difficulty: 'medium-low'}),
  7: levelConfig({level: 7, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'orangeBottle'],
    copiesByType: {blueFruit: 6, blueJuice: 6, blueMilk: 6, greenHerbal: 3, orangeBottle: 3},
    targetMatches: 8, difficulty: 'medium'}),
  8: levelConfig({level: 8, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'level3Milk', 'greenFruit', 'orangeCan'],
    copiesByType: {blueFruit: 6, blueJuice: 6, level3Milk: 6, greenFruit: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'medium'}),
  9: levelConfig({level: 9, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'blueMilk', 'greenFruit', 'orangeCan', 'redChips'],
    copiesByType: {blueFruit: 3, blueJuice: 6, blueMilk: 6, greenFruit: 3, orangeCan: 3, redChips: 3},
    targetMatches: 8, difficulty: 'medium-plus'}),
  10: levelConfig({level: 10, rows: 5, columns: 6,
    productTypes: ['greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {greenBottle: 6, greenHerbal: 6, level3Milk: 6, orangeBottle: 6, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'first-challenge'}),
  11: levelConfig({level: 11, rows: 4, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'juice', 'blueFruit', 'blueMilk', 'orangeBottle', 'redChips'],
    copiesByType: {apple: 3, milk: 3, can: 3, juice: 3, blueFruit: 3, blueMilk: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 8, difficulty: 'medium-entry'}),
  12: levelConfig({level: 12, rows: 4, columns: 6,
    productTypes: ['juice', 'blueMilk', 'orangeBottle', 'greenHerbal', 'apple', 'blueJuice', 'greenBottle', 'orangeCan'],
    copiesByType: {juice: 3, blueMilk: 3, orangeBottle: 3, greenHerbal: 3, apple: 3, blueJuice: 3, greenBottle: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'medium-entry'}),
  13: levelConfig({level: 13, rows: 4, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'level3Milk', 'redChips', 'greenBottle', 'orangeCan', 'greenFruit', 'orangeBottleAlt'],
    copiesByType: {blueFruit: 3, blueJuice: 3, level3Milk: 3, redChips: 3, greenBottle: 3, orangeCan: 3, greenFruit: 3, orangeBottleAlt: 3},
    targetMatches: 8, difficulty: 'medium'}),
  14: levelConfig({level: 14, rows: 4, columns: 6,
    productTypes: ['milk', 'can', 'greenFruit', 'orangeBottleAlt', 'blueMilk', 'greenHerbal', 'redChips', 'orangeCan'],
    copiesByType: {milk: 3, can: 3, greenFruit: 3, orangeBottleAlt: 3, blueMilk: 3, greenHerbal: 3, redChips: 3, orangeCan: 3},
    targetMatches: 8, difficulty: 'medium'}),
  15: levelConfig({level: 15, rows: 4, columns: 6,
    productTypes: ['apple', 'juice', 'blueJuice', 'redChips', 'orangeBottle', 'greenBottle', 'level3Milk', 'greenHerbal'],
    copiesByType: {apple: 3, juice: 3, blueJuice: 3, redChips: 3, orangeBottle: 3, greenBottle: 3, level3Milk: 3, greenHerbal: 3},
    targetMatches: 8, difficulty: 'medium'}),
  16: levelConfig({level: 16, rows: 5, columns: 6,
    productTypes: ['blueFruit', 'blueMilk', 'greenHerbal', 'orangeCan', 'redChips', 'apple', 'milk', 'blueJuice', 'greenBottle', 'orangeBottle'],
    copiesByType: {blueFruit: 3, blueMilk: 3, greenHerbal: 3, orangeCan: 3, redChips: 3, apple: 3, milk: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'medium-plus'}),
  17: levelConfig({level: 17, rows: 5, columns: 6,
    productTypes: ['milk', 'can', 'blueJuice', 'greenFruit', 'orangeBottleAlt', 'level3Milk', 'redChips', 'juice', 'blueFruit', 'greenHerbal'],
    copiesByType: {milk: 3, can: 3, blueJuice: 3, greenFruit: 3, orangeBottleAlt: 3, level3Milk: 3, redChips: 3, juice: 3, blueFruit: 3, greenHerbal: 3},
    targetMatches: 10, difficulty: 'medium-plus'}),
  18: levelConfig({level: 18, rows: 5, columns: 6,
    productTypes: ['apple', 'juice', 'orangeBottle', 'blueFruit', 'greenBottle', 'blueMilk', 'orangeCan', 'can', 'redChips', 'orangeBottleAlt'],
    copiesByType: {apple: 3, juice: 3, orangeBottle: 3, blueFruit: 3, greenBottle: 3, blueMilk: 3, orangeCan: 3, can: 3, redChips: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'medium-plus'}),
  19: levelConfig({level: 19, rows: 5, columns: 6,
    productTypes: ['blueFruit', 'blueJuice', 'greenHerbal', 'greenFruit', 'orangeBottleAlt', 'orangeCan', 'redChips', 'level3Milk', 'milk', 'can'],
    copiesByType: {blueFruit: 3, blueJuice: 3, greenHerbal: 3, greenFruit: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3, level3Milk: 3, milk: 3, can: 3},
    targetMatches: 10, difficulty: 'hard-entry'}),
  20: levelConfig({level: 20, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'can', 'juice', 'blueMilk', 'greenBottle', 'orangeBottle', 'redChips', 'blueFruit', 'greenFruit'],
    copiesByType: {apple: 3, milk: 3, can: 3, juice: 3, blueMilk: 3, greenBottle: 3, orangeBottle: 3, redChips: 3, blueFruit: 3, greenFruit: 3},
    targetMatches: 10, difficulty: 'challenge'}),
  21: levelConfig({level: 21, rows: 5, columns: 6,
    productTypes: ['teddy', 'juice', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'orangeCan', 'redChips'],
    copiesByType: {teddy: 3, juice: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard'}),
  22: levelConfig({level: 22, rows: 5, columns: 6,
    productTypes: ['teddy', 'can', 'blueFruit', 'blueJuice', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {teddy: 3, can: 3, blueFruit: 3, blueJuice: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard'}),
  23: levelConfig({level: 23, rows: 5, columns: 6,
    productTypes: ['teddy', 'milk', 'juice', 'can', 'blueFruit', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt', 'redChips'],
    copiesByType: {teddy: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard'}),
  24: levelConfig({level: 24, rows: 5, columns: 6,
    productTypes: ['teddy', 'can', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'orangeBottle', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {teddy: 3, can: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'hard-plus'}),
  25: levelConfig({level: 25, rows: 5, columns: 6,
    productTypes: ['teddy', 'blueJuice', 'apple', 'milk', 'blueFruit', 'greenFruit', 'greenHerbal', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {teddy: 3, blueJuice: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'milestone-hard'}),
  26: levelConfig({level: 26, rows: 5, columns: 6,
    productTypes: ['apple', 'greenFruit', 'juice', 'can', 'blueJuice', 'blueMilk', 'greenBottle', 'level3Milk', 'orangeBottleAlt', 'redChips'],
    copiesByType: {apple: 3, greenFruit: 3, juice: 3, can: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, level3Milk: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'hard-plus'}),
  27: levelConfig({level: 27, rows: 5, columns: 6,
    productTypes: ['can', 'blueJuice', 'apple', 'milk', 'blueFruit', 'greenFruit', 'greenHerbal', 'orangeBottle', 'orangeCan', 'level3Milk'],
    copiesByType: {can: 3, blueJuice: 3, apple: 3, milk: 3, blueFruit: 3, greenFruit: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, level3Milk: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  28: levelConfig({level: 28, rows: 5, columns: 6,
    productTypes: ['milk', 'blueMilk', 'juice', 'can', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {milk: 3, blueMilk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  29: levelConfig({level: 29, rows: 5, columns: 6,
    productTypes: ['duck', 'can', 'apple', 'milk', 'blueJuice', 'blueMilk', 'greenFruit', 'level3Milk', 'orangeBottle', 'redChips'],
    copiesByType: {duck: 3, can: 3, apple: 3, milk: 3, blueJuice: 3, blueMilk: 3, greenFruit: 3, level3Milk: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-hard'}),
  30: levelConfig({level: 30, rows: 5, columns: 6,
    productTypes: ['duck', 'orangeCan', 'juice', 'can', 'blueFruit', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt', 'redChips'],
    copiesByType: {duck: 3, orangeCan: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'milestone-challenge'}),
  31: levelConfig({level: 31, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'orangeBottle', 'orangeCan'],
    copiesByType: {apple: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced-entry'}),
  32: levelConfig({level: 32, rows: 5, columns: 6,
    productTypes: ['milk', 'can', 'blueFruit', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'orangeCan', 'redChips'],
    copiesByType: {milk: 3, can: 3, blueFruit: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  33: levelConfig({level: 33, rows: 5, columns: 6,
    productTypes: ['apple', 'juice', 'can', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt', 'redChips'],
    copiesByType: {apple: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced'}),
  34: levelConfig({level: 34, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'blueJuice', 'blueMilk', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeCan'],
    copiesByType: {apple: 3, milk: 3, juice: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced-plus'}),
  35: levelConfig({level: 35, rows: 5, columns: 6,
    productTypes: ['teddy', 'duck', 'can', 'blueFruit', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'redChips'],
    copiesByType: {teddy: 3, duck: 3, can: 3, blueFruit: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-milestone'}),
  36: levelConfig({level: 36, rows: 5, columns: 6,
    productTypes: ['apple', 'milk', 'juice', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {apple: 3, milk: 3, juice: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-hard'}),
  37: levelConfig({level: 37, rows: 5, columns: 6,
    productTypes: ['teddy', 'milk', 'can', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'level3Milk', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {teddy: 3, milk: 3, can: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'advanced-hard'}),
  38: levelConfig({level: 38, rows: 5, columns: 6,
    productTypes: ['duck', 'apple', 'juice', 'can', 'blueFruit', 'blueMilk', 'greenHerbal', 'level3Milk', 'orangeBottle', 'redChips'],
    copiesByType: {duck: 3, apple: 3, juice: 3, can: 3, blueFruit: 3, blueMilk: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 10, difficulty: 'advanced-hard-plus'}),
  39: levelConfig({level: 39, rows: 5, columns: 6,
    productTypes: ['teddy', 'duck', 'milk', 'blueFruit', 'blueJuice', 'greenBottle', 'greenFruit', 'orangeBottle', 'orangeBottleAlt', 'orangeCan'],
    copiesByType: {teddy: 3, duck: 3, milk: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3, orangeBottleAlt: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'expert-entry'}),
  40: levelConfig({level: 40, rows: 5, columns: 6,
    productTypes: ['teddy', 'duck', 'apple', 'can', 'blueJuice', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'redChips'],
    copiesByType: {teddy: 3, duck: 3, apple: 3, can: 3, blueJuice: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert-milestone'}),
  41: levelConfig({level: 41, rows: 5, columns: 6,
    productTypes: ['corn', 'milk', 'juice', 'can', 'blueFruit', 'blueJuice', 'greenBottle', 'greenFruit', 'orangeBottle', 'redChips'],
    copiesByType: {corn: 3, milk: 3, juice: 3, can: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert'}),
  42: levelConfig({level: 42, rows: 5, columns: 6,
    productTypes: ['corn', 'milk', 'can', 'blueFruit', 'blueMilk', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'orangeCan', 'redChips'],
    copiesByType: {corn: 3, milk: 3, can: 3, blueFruit: 3, blueMilk: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, orangeCan: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert'}),
  43: levelConfig({level: 43, rows: 5, columns: 6,
    productTypes: ['corn', 'duck', 'apple', 'juice', 'blueFruit', 'blueJuice', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottle'],
    copiesByType: {corn: 3, duck: 3, apple: 3, juice: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'expert-plus'}),
  44: levelConfig({level: 44, rows: 5, columns: 6,
    productTypes: ['corn', 'teddy', 'duck', 'milk', 'can', 'blueJuice', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottleAlt'],
    copiesByType: {corn: 3, teddy: 3, duck: 3, milk: 3, can: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'expert-plus'}),
  45: levelConfig({level: 45, rows: 5, columns: 6,
    productTypes: ['corn', 'teddy', 'duck', 'apple', 'juice', 'blueFruit', 'blueMilk', 'greenFruit', 'greenHerbal', 'orangeBottle'],
    copiesByType: {corn: 3, teddy: 3, duck: 3, apple: 3, juice: 3, blueFruit: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'expert-challenge'}),
  46: levelConfig({level: 46, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'blueFruit', 'blueJuice', 'greenBottle', 'greenHerbal', 'level3Milk', 'orangeBottleAlt', 'redChips'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, greenHerbal: 3, level3Milk: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 10, difficulty: 'expert-hard'}),
  47: levelConfig({level: 47, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'teddy', 'apple', 'blueMilk', 'greenBottle', 'greenFruit', 'level3Milk', 'orangeBottle'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, teddy: 3, apple: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, level3Milk: 3, orangeBottle: 3},
    targetMatches: 10, difficulty: 'expert-hard'}),
  48: levelConfig({level: 48, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'duck', 'blueFruit', 'blueJuice', 'blueMilk', 'greenHerbal', 'orangeBottle', 'orangeBottleAlt'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, duck: 3, blueFruit: 3, blueJuice: 3, blueMilk: 3, greenHerbal: 3, orangeBottle: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'expert-hard-plus'}),
  49: levelConfig({level: 49, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueFruit', 'blueMilk', 'greenBottle', 'greenFruit', 'orangeBottleAlt'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, greenFruit: 3, orangeBottleAlt: 3},
    targetMatches: 10, difficulty: 'master-entry'}),
  50: levelConfig({level: 50, rows: 5, columns: 6,
    productTypes: ['corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'level3Milk', 'orangeBottle', 'orangeCan'],
    copiesByType: {corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, level3Milk: 3, orangeBottle: 3, orangeCan: 3},
    targetMatches: 10, difficulty: 'world-1-finale'}),
  51: levelConfig({level: 51, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'milk', 'blueFruit', 'blueJuice', 'greenBottle', 'orangeBottle', 'redChips'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, milk: 3, blueFruit: 3, blueJuice: 3, greenBottle: 3, orangeBottle: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-entry'}),
  52: levelConfig({level: 52, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'can', 'blueMilk', 'greenFruit', 'greenHerbal', 'level3Milk', 'orangeCan'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, can: 3, blueMilk: 3, greenFruit: 3, greenHerbal: 3, level3Milk: 3, orangeCan: 3},
    targetMatches: 12, difficulty: 'world-2-easy'}),
  53: levelConfig({level: 53, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'juice', 'blueFruit', 'blueMilk', 'greenBottle', 'orangeBottleAlt', 'redChips'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, juice: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-easy-plus'}),
  54: levelConfig({level: 54, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'milk', 'blueJuice', 'greenFruit', 'level3Milk', 'orangeBottle'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, milk: 3, blueJuice: 3, greenFruit: 3, level3Milk: 3, orangeBottle: 3},
    targetMatches: 12, difficulty: 'world-2-medium'}),
  55: levelConfig({level: 55, rows: 6, columns: 6,
    productTypes: ['pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'apple', 'can', 'blueFruit', 'greenHerbal', 'orangeBottle', 'orangeCan', 'redChips'],
    copiesByType: {pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, apple: 3, can: 3, blueFruit: 3, greenHerbal: 3, orangeBottle: 3, orangeCan: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-milestone'}),
  56: levelConfig({level: 56, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'blueFruit', 'blueMilk', 'greenBottle', 'orangeBottleAlt', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, blueFruit: 3, blueMilk: 3, greenBottle: 3, orangeBottleAlt: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-medium-plus'}),
  57: levelConfig({level: 57, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'milk', 'blueJuice', 'greenFruit', 'level3Milk'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, milk: 3, blueJuice: 3, greenFruit: 3, level3Milk: 3},
    targetMatches: 12, difficulty: 'world-2-advanced-entry'}),
  58: levelConfig({level: 58, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'duck', 'can', 'blueMilk', 'greenHerbal', 'orangeCan'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, duck: 3, can: 3, blueMilk: 3, greenHerbal: 3, orangeCan: 3},
    targetMatches: 12, difficulty: 'world-2-advanced'}),
  59: levelConfig({level: 59, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueFruit', 'greenBottle', 'orangeBottle'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueFruit: 3, greenBottle: 3, orangeBottle: 3},
    targetMatches: 12, difficulty: 'world-2-advanced-plus'}),
  60: levelConfig({level: 60, rows: 6, columns: 6,
    productTypes: ['watermelon', 'strawberry', 'pineapple', 'sooperBiscuit', 'corn', 'grapes', 'lemon', 'teddy', 'duck', 'blueJuice', 'greenHerbal', 'redChips'],
    copiesByType: {watermelon: 3, strawberry: 3, pineapple: 3, sooperBiscuit: 3, corn: 3, grapes: 3, lemon: 3, teddy: 3, duck: 3, blueJuice: 3, greenHerbal: 3, redChips: 3},
    targetMatches: 12, difficulty: 'world-2-milestone'}),
};

export function getStarsForTime(timeLeft, durationSeconds) {
  if (durationSeconds <= 0) return 1;
  const remaining = timeLeft / durationSeconds;
  if (remaining >= 0.35) return 3;
  if (remaining >= 0.15) return 2;
  return 1;
}
