export const PRODUCT_ASSETS = {
  apple: require('../assets/splash elements/apple without bg.png'),
  milk: require('../assets/splash elements/milk bottle without bg.png'),
  juice: require('../assets/splash elements/orange bottle wthout bg.png'),
  can: require('../assets/splash elements/red bottle without bg.png'),
  blueMilk: require('../assets/merglix game elments/blue milk bottle.png'),
  blueJuice: require('../assets/merglix game elments/blue juice bottle.png'),
  orangeBottle: require('../assets/merglix game elments/orange bottle.png'),
  redChips: require('../assets/merglix game elments/red chips cane.png'),
  greenHerbal: require('../assets/merglix game elments/Green herbal bottle.png'),
  blueFruit: require('../assets/merglix game elments/blue fruit bottle.png'),
  greenBottle: require('../assets/merglix game elments/Green bottle.png'),
  greenFruit: require('../assets/merglix game elments/green fruit bottle.png'),
  level3Milk: require('../assets/merglix game elments/milk bottle.png'),
  orangeBottleAlt: require('../assets/merglix game elments/orange bottle-1.png'),
  orangeCan: require('../assets/merglix game elments/orange cane.png'),
};

export const SHELF_ASSETS = {
  classic3: require('../assets/cupboard with 3 shelf.png'),
  merglix4: require('../assets/merglix game elments/Gameplay shelf 01.png'),
};

export const LEVEL_CONFIGS = {
  1: {
    level: 1,
    rows: 3,
    columns: 4,
    productTypes: ['apple', 'milk', 'juice', 'can'],
    copiesPerType: 3,
    matchSize: 3,
    matchReward: 3,
    completionReward: 0,
    durationSeconds: 150,
    difficulty: 'easy',
    shelf: 'classic3',
    targetMatches: 4,
    starThresholds: {three: 100, two: 50},
  },
  2: {
    level: 2,
    rows: 3,
    columns: 5,
    productTypes: [
      'blueMilk',
      'blueJuice',
      'orangeBottle',
      'redChips',
      'greenHerbal',
    ],
    copiesByType: {
      blueMilk: 3,
      blueJuice: 3,
      orangeBottle: 3,
      redChips: 3,
      greenHerbal: 3,
    },
    matchSize: 3,
    matchReward: 3,
    completionReward: 0,
    durationSeconds: 135,
    difficulty: 'easy-medium',
    shelf: 'classic3',
    targetMatches: 5,
    starThresholds: {three: 90, two: 45},
  },
  3: {
    level: 3,
    rows: 3,
    columns: 6,
    productTypes: [
      'blueFruit',
      'greenBottle',
      'greenFruit',
      'level3Milk',
      'orangeBottleAlt',
      'orangeCan',
    ],
    copiesPerType: 3,
    matchSize: 3,
    matchReward: 3,
    completionReward: 0,
    durationSeconds: 150,
    difficulty: 'medium',
    shelf: 'classic3',
    targetMatches: 6,
    starThresholds: {three: 105, two: 55},
  },
};
